export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#ffdad6",
        "on-primary-container": "#778598",
        "on-secondary-fixed": "#002117",
        "primary-fixed-dim": "#bac8dc",
        "surface-container-highest": "#e2e2e3",
        "on-secondary": "#ffffff",
        "primary-fixed": "#d6e4f9",
        "on-secondary-container": "#306d58",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#95d3ba",
        "tertiary-fixed-dim": "#ecc070",
        "secondary-fixed": "#b0f0d6",
        "inverse-primary": "#bac8dc",
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#ffdea6",
        "on-error": "#ffffff",
        "on-surface-variant": "#44474c",
        "surface-container": "#eeeeef",
        "secondary-container": "#adedd3",
        "on-tertiary-fixed": "#271900",
        "surface-container-high": "#e8e8e9",
        "outline-variant": "#c4c6cc",
        "primary": "#000000",
        "surface-bright": "#f9f9fa",
        "tertiary": "#000000",
        "primary-container": "#0f1c2c",
        "surface": "#f9f9fa",
        "on-tertiary-container": "#a37e35",
        "on-background": "#1a1c1d",
        "surface-dim": "#dadadb",
        "secondary": "#2b6954",
        "surface-container-low": "#f3f3f4",
        "surface-variant": "#e2e2e3",
        "on-surface": "#1a1c1d",
        "on-secondary-fixed-variant": "#0b513d",
        "outline": "#74777d",
        "on-primary-fixed-variant": "#3a4859",
        "tertiary-container": "#271900",
        "on-tertiary-fixed-variant": "#5e4200",
        "error": "#ba1a1a",
        "background": "#f9f9fa",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#0f1c2c",
        "inverse-on-surface": "#f0f1f2",
        "surface-tint": "#525f71",
        "inverse-surface": "#2f3132"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "serif": ["Newsreader", "serif"],
        "body": ["Manrope", "sans-serif"],
        "sans": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
